var app=angular.module("app",['ui.router'])
app.run(function($rootScope){
	$rootScope.showFooter=true;
	$rootScope.$on("$stateChangeStart",function(e,toState,toParams,fromState,fromParams){
		var url=toState.name.split(".")[1];
//		console.log(url)
		switch(url){
			case "home":
			$rootScope.currentIndex=0;
			$rootScope.showFooter=true;
			break;
			case "list":
			$rootScope.currentIndex=1;
			$rootScope.showFooter=true;
			break;
			case "cart":
			$rootScope.currentIndex=2;
			$rootScope.showFooter=false;
			break;
			case "mine":
			$rootScope.currentIndex=3;
			$rootScope.showFooter=true;
			break;
			default:
			$rootScope.showFooter=true;
			break;
		}
	})
})
app.config(function($urlRouterProvider){
	$urlRouterProvider.otherwise("/footer/home/article1")
})
app.config(["$stateProvider",function($stateProvider){
		$stateProvider
		.state("footer",{
			url:"/footer",
			templateUrl:"html/footer.html"
		})
		.state("footer.home",{
			url:"/home",
			templateUrl:"html/home.html",
			controller:"homeController"
		})
		.state("footer.home.article1",{
			url:"/article1",
			views:{
				"article1":{
					templateUrl:"html/article1.html",
				}
			}
		})
		.state("footer.home.article2",{
			url:"/article2",
			views:{
				"article2":{
					templateUrl:"html/article2.html",
				}
			}
		})
		.state("footer.home.article3",{
			url:"/article3",
			views:{
				"article3":{
					templateUrl:"html/article3.html",
				}
			}
		})
		.state("footer.home.article4",{
			url:"/article4",
			views:{
				"article4":{
					templateUrl:"html/article4.html",
				}
			}
		})
		.state("footer.list",{
			url:"/list/:name?",
			templateUrl:"html/list.html",
			controller:"listController"
		})
		.state("footer.mine",{
			url:"/mine",
			templateUrl:"html/mine.html",
			controller:"mineController"
		})	
		.state("footer.cart",{
			url:"/cart",
			templateUrl:"html/cart.html",
			controller:"carController"
		})
		.state("goodsDetails",{
			url:"/l_goodsDetails/:id",
			templateUrl:"html/l_goodsDetails.html",
			controller:"l_goodsDetailsController"
		})
		.state("goodsDetails.tuwendetail",{
			url:"/tuwendetail/:id",
			templateUrl:"html/tuwendetail.html",    //接收参数
		})
		.state("goodsDetails.pinglun",{
			url:"/pinglun/:id",
			templateUrl:"html/pinglun.html",
			controller:"pinglunController"
		})
		.state("footer.order",{
			url:"/order",
			templateUrl:"html/order.html",
		})
		.state("purse",{
			url:"/purse",
			templateUrl:"html/purse.html",
		})
		.state("login",{
			url:"/login",
			templateUrl:"html/login.html",
			controller:"loginController"
		})
		.state("regist",{
			url:"/regist",
			templateUrl:"html/regist.html",
			controller:"registController"
		})
		.state("article_detail",{
			url:"/article_detail/:id",
			templateUrl:"html/article_detail.html",
			controller:"article_detailController"
		})
		.state("collect",{
			url:"/collect",
			templateUrl:"html/collect.html"
		})
		.state("order",{
			url:"/order",
			templateUrl:"html/order.html"
		})
		.state("redpacket",{
			url:"/redpacket",
			templateUrl:"html/redpacket.html"
		})
}])
